### ISSUE TITLE
no response from hoverboard mobo

### ISSUE THREAD

**Issue by s1mionrobert** [jnsw/bt2bp#6]
hi, i have a problem with this project, i managed to flash the motherboard and the esp 32 with bipropellant and i connected  them properly but nothing happens when i connect and try to control them with the app.

Do i need to change something in the esp32 code?

**Comment by jnsw** [comment]
how did you managed to find the app? maybe youve got the wrong one

**Comment by s1mionrobert** [comment]
I downloaded it from your link, it connects to esp32 but it says disconnected.

**Comment by jnsw** [comment]
thats part of the app developer, but unfortunately he discontinued the app, maybe writing him on arducontrolapp@gmail.com or contacting him here https://www.instagram.com/arducontrol/ could fix the issue

**Comment by s1mionrobert** [comment]
I don't know if the app is the problem. It looks like it's connecting
because it does not say lost connection or anything when I try to control
the esp, it only does that when I unplug the esp from power
